### ISSUE TITLE
Anguar application error reports result in recursive "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by mattmcardle** [rollbar/rollbar.js#425]
All errors in my Angular application seem to be resulting in  Maximum call stack size exceeded after the error is reported to rollbar. I have recreated this in a brand new Angular application and uploaded it here: https://github.com/mattmcardle/rollbar-issue-demo.

Note, the error demo uses the Angular CLI. The accessToken has also been removed from the rollbar configuration object and replaced with `xyz`, this can be found in the app.module.ts

**Comment by rokob** [comment]
I'm looking into this, but quick question why is Rollbar not in your package.json as a dependency? It would seem that running it as is would not be possible.

**Comment by mattmcardle** [comment]
Ah, I forgot to save it when i done the npm install, fixed now!

**Comment by likebeats** [comment]
Was able to avoid these recursive loops by disabling network telemetry for now.
```
_rollbarConfig = {
  ...
  autoInstrument: {
    network: false,
  ...
  }
  ...
}
```

**Comment by achimha** [comment]
The `autoInstrument` config value did not solve the problem for me. I went back to rollbar 2.2.2 to get rid of the infinite recursion.

**Comment by rokob** [comment]
So this is a bug in zone.js: https://github.com/angular/zone.js/issues/886

**Comment by rokob** [comment]
https://github.com/angular/zone.js/commit/a66595af18d4c42584401dd2df387b02cb01d8d9#diff-f5e084bcb7c43d977d56c3b791bbca2d is the commit that broke it which is in 0.8.17, 0.8.16 should work. There is already a fix committed to master and should be picked up in the next release. The reason setting `network: false` could cause this to stop is because that is one place where we wrap a function. You might also see it in other cases. I have a feeling that telemetry as a whole due to wrapping could cause this to come out depend on the code paths you hit which is why reverting to 2.1.3 might work, but 2.2.2 should still cause this if you are on 0.8.17 of zone.js

**Comment by rokob** [comment]
I'm going to close this as it is an upstream bug
